services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: famlink_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: famlink_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: famlink_db
      PORT: 3001
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "8822:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  db-data:
